apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:elasticsearch
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:vmware-system-restricted
subjects:
- kind: ServiceAccount

  name: {{ include "charts.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elasticsearch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "charts.fullname" . }}:config-reader
subjects:
- kind: ServiceAccount
  name: {{ include "charts.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "charts.fullname" . }}:config-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  resourceNames: ["elasticsearch"]
  verbs: ["get", "list"]
- apiGroups:
    - extensions
    - networking.k8s.io
  resources:
    - ingresses
    - services
    - pods
  verbs:
    - get
    - watch
    - list

